export { Start } from 'features/Home/pages'
export { Login } from 'features/Home/pages'
export { Register } from 'features/Home/pages'
export { Quiz } from 'features/Home/pages'
export { Result } from 'features/Home/pages'
export { homeApi } from 'features/Home/state/api/homeApi'
